import Head from "next/head";
import BannerFooter from "../components/BannerFooter";
import BannerHero from "../components/BannerHero";
import BestProducts from "../components/BestProducts";
interface HomeProps {
  data: {
    _id: string;
    title: string;
    description: string;
    price: number;
    category: string;
    image: string[];
  }[];
}
export default function Home({ data }: HomeProps) {
  return (
    <>
      <Head>
        <title>Sba E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="px-6 md:px-10 lg:px-12 py-6 flex flex-col gap-20 items-center">
        <BannerHero />
        <BestProducts products={data} />
        <BannerFooter />
      </main>
    </>
  );
}
export const getServerSideProps = async () => {
  const response = await fetch(process.env.NEXT_PUBLIC_BASE_URL + "products");
  const data = await response.json();
  return {
    props: { data },
  };
};
